name: Publish Docker image

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get latest tag from OpenRGB
        run: |
          git clone https://gitlab.com/CalcProgrammer1/OpenRGB
          cd OpenRGB
          echo "TAG_TO_BUILD=$(git describe --abbrev=0)" >> $GITHUB_ENV

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Limit concurrent builds to 1
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args:
            OPENRGB_VERSION=${{ env.TAG_TO_BUILD }}
          push: true
          tags:
            codetheweb/openrgb-server:${{ env.TAG_TO_BUILD }}
            codetheweb/openrgb-server:latest
          platforms: linux/amd64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v2.4.3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: codetheweb/openrgb-server
          short-description: ${{ github.event.repository.description }}
